const LocationTypes = {
  GET_LOCATION_START: "GET_LOCATION_START",
  GET_LOCATION_SUCCESS: "GET_LOCATION_SUCCESS",
  GET_LOCATION_FAILURE: "GET_LOCATION_FAILURE",
  SET_CITY: "SET_CITY",
  SET_COORDINATES: "SET_COORDINATES"
};

export default LocationTypes;
