const RestaurantsTypes = {
  GET_YELP_RESTAURANTS_START_BY_SEARCH: "GET_YELP_RESTAURANTS_START_SEARCH",
  GET_YELP_RESTAURANTS_START_BY_COORD: "GET_YELP_RESTAURANTS_START_COORD",
  GET_YELP_RESTAURANTS_SUCCESS: "GET_YELP_RESTAURANTS_SUCCESS",
  GET_YELP_RESTAURANTS_FAILURE: "GET_YELP_RESTAURANTS_FAILURE"
};

export default RestaurantsTypes;
