const RestaurantsTypes = {
  GET_YELP_RESTAURANTS_START: "GET_YELP_RESTAURANTS_START",
  GET_YELP_RESTAURANTS_SUCCESS: "GET_YELP_RESTAURANTS_SUCCESS",
  GET_YELP_RESTAURANTS_FAILURE: "GET_YELP_RESTAURANTS_FAILURE"
};

export default RestaurantsTypes;
