const SearchTypes = {
  STARTED_TYPING_IN_SEARCH: "STARTED_TYPING_IN_SEARCH",
  GOT_AUTOCOMPLETE_SUCCESS: "GOT_AUTOCOMPLETE_SUCCESS",
  GOT_AUTOCOMPLETE_FAILURE: "GOT_AUTOCOMPLETE_FAILURE"
};
export default SearchTypes;
